/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.registershift;

import controller.EmployeeDAO;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Employee;
import view.login.HomeFrm;

/**
 *
 * @author Admin
 */
public class SearchEmployeeRegisterShiftFrm extends javax.swing.JFrame {

    /**
     * Creates new form DangKyCaLamFrm
     */
    
    private ArrayList<Employee> listEmployee;
    DefaultTableModel tm;
    EmployeeDAO employeeDAO = new EmployeeDAO();
    
    public SearchEmployeeRegisterShiftFrm() {
        initComponents();
        
        setTitle("Đăng ký ca làm tuần tới");
        setSize(620, 380);
        setLocationRelativeTo(this);
        getContentPane().setBackground(Color.white);
        
        String[] cols = {"MNV", "Tên", "Email", "Sđt", "Địa chỉ"};
        tm = new DefaultTableModel(cols, 0);
        tblEmployee.setModel(tm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSearch = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSearch.setBackground(new java.awt.Color(233, 110, 21));
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Tìm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        backBtn.setText("<");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Đăng ký ca làm tuần tới");

        txtName.setText(" ");

        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEmployee.setFocusable(false);
        tblEmployee.setGridColor(new java.awt.Color(255, 255, 255));
        tblEmployee.setOpaque(false);
        tblEmployee.setRequestFocusEnabled(false);
        tblEmployee.setRowSelectionAllowed(false);
        tblEmployee.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tblEmployee.setShowGrid(false);
        tblEmployee.setUpdateSelectionOnSort(false);
        tblEmployee.setVerifyInputWhenFocusTarget(false);
        tblEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmployeeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmployee);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnSearch))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        listEmployee = employeeDAO.searchEmployee(txtName.getText().trim());
        if (listEmployee.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Danh sách trống");
        } else {
            String[][] data = new String[listEmployee.size()][5];
            for(int i=0 ; i<listEmployee.size();i++){
                var nhanVien = listEmployee.get(i);
                data[i][0] = nhanVien.getId()+"";
                data[i][1] = nhanVien.getName();
                data[i][2] = nhanVien.getEmail();
                data[i][3] = nhanVien.getPhoneNumber();
                data[i][4] = nhanVien.getAddress();
            }
        
            String[] cols = {"MNV", "Tên", "Email", "Sđt", "Địa chỉ"};
            tm = new DefaultTableModel(data, cols);
            tblEmployee.setModel(tm);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        (new HomeFrm()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void tblEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmployeeMouseClicked
        // TODO add your handling code here:
        int row = tblEmployee.getSelectedRow();
        if (row >= 0 && row <= tblEmployee.getRowCount()-1) {
            int id = Integer.parseInt(tm.getValueAt(row, 0).toString());
            String name = tm.getValueAt(row, 1).toString();
            String email = tm.getValueAt(row, 2).toString();
            String phoneNumber = tm.getValueAt(row, 3).toString();
            String address = tm.getValueAt(row, 4).toString();
            Employee employee = new Employee(id, name, email, phoneNumber, address);
            (new RegisterShiftFrm(employee)).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_tblEmployeeMouseClicked
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmployee;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
