/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.checkin;

import controller.CheckInOutDAO;
import controller.NhanVienDAO;
import java.awt.Color;
import java.util.Date;
import javax.swing.JOptionPane;
import model.CheckInOut;
import model.NhanVien;
import view.user.TrangChuFrm;

/**
 *
 * @author Admin
 */
public class CheckInFrm extends javax.swing.JFrame {

    /**
     * Creates new form CheckInFrm
     */
    CheckInOutDAO checkInOutDAO = new CheckInOutDAO();
    NhanVienDAO nhanVienDAO = new NhanVienDAO();
    
    public CheckInFrm() {
        initComponents();
        
        setTitle("Check In");
        setSize(620, 380);
        setLocationRelativeTo(this);
        getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mnvCheckInTxt = new javax.swing.JTextField();
        submitCheckInBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Check In");

        mnvCheckInTxt.setText(" ");

        submitCheckInBtn.setBackground(new java.awt.Color(233, 110, 21));
        submitCheckInBtn.setForeground(new java.awt.Color(255, 255, 255));
        submitCheckInBtn.setText("Submit");
        submitCheckInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitCheckInBtnActionPerformed(evt);
            }
        });

        backBtn.setText("<");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(mnvCheckInTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(submitCheckInBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161)
                        .addComponent(jLabel1)))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backBtn))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mnvCheckInTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitCheckInBtn))
                .addContainerGap(272, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitCheckInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitCheckInBtnActionPerformed
        // TODO add your handling code here:
        if (mnvCheckInTxt.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nhập mã nhân viên!");
        } else {
            int mnv = Integer.parseInt(mnvCheckInTxt.getText().trim());
            if (nhanVienDAO.checkNhanVienById(mnv)) {
                NhanVien nhanVien = nhanVienDAO.getNhanVienById(mnv);
                Date gioCheckIn = currentTime();
                Date gioCheckOut = null;
                Date ngay = currentTime();
                CheckInOut checkInOut = new CheckInOut(nhanVien, gioCheckIn, gioCheckOut, ngay);
                if (!checkInOutDAO.checkCheckIn(checkInOut)) {
                    if (checkInOutDAO.insertCheckIn(checkInOut)) {
                        JOptionPane.showMessageDialog(this, "Check In thành công");
                        (new TrangChuFrm()).setVisible(true);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Check In thất bại");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "MNV: " + mnv + " đã check in ca làm");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy MNV: " + mnv);
            }
        }
    }//GEN-LAST:event_submitCheckInBtnActionPerformed

    public Date currentTime() {
        return new Date();
    }
  
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        (new TrangChuFrm()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField mnvCheckInTxt;
    private javax.swing.JButton submitCheckInBtn;
    // End of variables declaration//GEN-END:variables
}
