/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.dangkycalam;

import controller.LichDangKyDAO;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.LichDangKy;
import model.NhanVien;
import view.user.TrangChuFrm;

/**
 *
 * @author Admin
 */
public class DangKyCaLamFrm extends javax.swing.JFrame {

    /**
     * Creates new form DangKyCaLamFrm
     */
    
    private NhanVien nhanVien;
    DefaultTableModel tm;

    public DangKyCaLamFrm(NhanVien nhanVien) {
        this.nhanVien = nhanVien;
        initComponents();
        
        setTitle("Đăng ký ca làm tuần tới");
        setSize(620, 380);
        setLocationRelativeTo(this);
        getContentPane().setBackground(Color.white);
        
        mnvTxt.setText(String.valueOf(nhanVien.getId()));
        tenTxt.setText(nhanVien.getTen());
        emailTxt.setText(nhanVien.getEmail());
        diaChiTxt.setText(nhanVien.getDiaChi());
        sdtTxt.setText(nhanVien.getSdt());
        
        // Set thời gian tuần tới
        String firstDayNextWeek = new SimpleDateFormat("dd/MM/yyyy").format(firstDayNextWeek());
        String lastDayNextWeek = new SimpleDateFormat("dd/MM/yyyy").format(lastDayNextWeek());
        thoiGianTxt.setText(firstDayNextWeek + " - " + lastDayNextWeek);
        thoiGianTxt.setHorizontalAlignment(JTextField.CENTER);
        
        // tạo bảng đăng ký
        tm = new DefaultTableModel() {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return switch (columnIndex) {
                    case 0 -> String.class;
                    case 1 -> Boolean.class;
                    default -> Boolean.class;
                };
            }
        };
        dangKytbl.setModel(tm);
        tm.addColumn("Thứ");
        tm.addColumn("Ca 1");
        tm.addColumn("Ca 2");
        int row = 0;
        for (int i = 2; i <= 8; i++){
            tm.addRow(new Object[0]);
            if (i == 8) {
                tm.setValueAt("CN", row, 0);
            } else {
                tm.setValueAt(String.valueOf(i), row, 0);
            }
            tm.setValueAt(false, row, 1);
            tm.setValueAt(false, row, 2);
            row++;
        }
    }
    
    private Date firstDayNextWeek() {
        Calendar calendar = Calendar.getInstance();
        String dayString = new SimpleDateFormat("EEEE").format(calendar.getTime());
        while (!"Monday".equals(dayString)) {
            calendar.add(Calendar.DATE, 1);
            dayString = new SimpleDateFormat("EEEE").format(calendar.getTime());
        }
        return calendar.getTime();
    }
    
    private Date lastDayNextWeek() {
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(firstDayNextWeek());
        calendar.add(Calendar.DATE, 6);
        return calendar.getTime();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mnvTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tenTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        diaChiTxt = new javax.swing.JTextField();
        sdtTxt = new javax.swing.JTextField();
        thoiGianTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        dangKytbl = new javax.swing.JTable();
        luuBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backBtn.setText("<");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Đăng ký ca làm tuần tới");

        jLabel2.setText("MNV: ");

        mnvTxt.setEditable(false);

        jLabel3.setText("Email: ");

        tenTxt.setEditable(false);

        jLabel4.setText("Địa chỉ: ");

        jLabel5.setText("SĐT: ");

        jLabel6.setText("Tên NV: ");

        emailTxt.setEditable(false);

        diaChiTxt.setEditable(false);
        diaChiTxt.setText(" ");

        sdtTxt.setEditable(false);

        thoiGianTxt.setEditable(false);
        thoiGianTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoiGianTxtActionPerformed(evt);
            }
        });

        dangKytbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(dangKytbl);

        luuBtn.setBackground(new java.awt.Color(233, 110, 21));
        luuBtn.setForeground(new java.awt.Color(255, 255, 255));
        luuBtn.setText("Lưu");
        luuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mnvTxt)
                    .addComponent(tenTxt)
                    .addComponent(emailTxt)
                    .addComponent(diaChiTxt)
                    .addComponent(sdtTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(luuBtn)
                        .addGap(143, 143, 143))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(thoiGianTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thoiGianTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(mnvTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(diaChiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sdtTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(luuBtn))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        (new TimKiemNhanVienFrm()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void luuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuBtnActionPerformed
        // TODO add your handling code here:
        Boolean showDialog = false;
        for (int i=0; i<=6; i++) {
            Boolean caSang = (Boolean) tm.getValueAt(i, 1);
            Boolean caToi = (Boolean) tm.getValueAt(i, 2);
            Calendar calendar = Calendar.getInstance();
            calendar.setTime(firstDayNextWeek());
            calendar.add(Calendar.DATE, i);
            Date ngay = calendar.getTime();
            Boolean chapNhan = false;
            LichDangKy lichDangKy = new LichDangKy(nhanVien, caSang, caToi, ngay, chapNhan);
            LichDangKyDAO dangKyCaLamDAO = new LichDangKyDAO();
            showDialog = dangKyCaLamDAO.insertLichDangKy(lichDangKy);
        }
        if(showDialog){
            JOptionPane.showMessageDialog(this, "Lưu thành công");
            (new TrangChuFrm()).setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Lưu thất bại");
        }
    }//GEN-LAST:event_luuBtnActionPerformed

    private void thoiGianTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoiGianTxtActionPerformed
        // TODO add your handling code here  
    }//GEN-LAST:event_thoiGianTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTable dangKytbl;
    private javax.swing.JTextField diaChiTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton luuBtn;
    private javax.swing.JTextField mnvTxt;
    private javax.swing.JTextField sdtTxt;
    private javax.swing.JTextField tenTxt;
    private javax.swing.JTextField thoiGianTxt;
    // End of variables declaration//GEN-END:variables
}
