/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.dangkycalam;

import controller.DangKyCaLamDAO;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.NhanVien;
import view.user.TrangChuFrm;

/**
 *
 * @author Admin
 */
public class TimKiemNhanVienFrm extends javax.swing.JFrame {

    /**
     * Creates new form DangKyCaLamFrm
     */
    
    private ArrayList<NhanVien> nhanViens;
    DefaultTableModel tm;
    DangKyCaLamDAO dangKyCaLamDAO = new DangKyCaLamDAO();
    
    public TimKiemNhanVienFrm() {
        initComponents();
        
        setTitle("Đăng ký ca làm tuần tới");
        setSize(620, 380);
        setLocationRelativeTo(this);
        getContentPane().setBackground(Color.white);
        
        String[] cols = {"MNV", "Tên NV"};
        tm = new DefaultTableModel(cols, 0);
        nhanVienTbl.setModel(tm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tenTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        nhanVienTbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        timBtn.setBackground(new java.awt.Color(233, 110, 21));
        timBtn.setForeground(new java.awt.Color(255, 255, 255));
        timBtn.setText("Tìm");
        timBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timBtnActionPerformed(evt);
            }
        });

        backBtn.setText("<");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Đăng ký ca làm tuần tới");

        tenTxt.setText(" ");

        nhanVienTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        nhanVienTbl.setGridColor(new java.awt.Color(255, 255, 255));
        nhanVienTbl.setSelectionBackground(new java.awt.Color(255, 255, 255));
        nhanVienTbl.setShowGrid(false);
        nhanVienTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nhanVienTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(nhanVienTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(tenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(timBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timBtn))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void timBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timBtnActionPerformed
        // TODO add your handling code here:
        nhanViens = dangKyCaLamDAO.getNhanViens(tenTxt.getText().trim());
        if (nhanViens.size() == 0) {
            JOptionPane.showMessageDialog(this, "Danh sách trống");
        }
        else{
            String[][] data = new String[nhanViens.size()][2];
        for(int i=0 ; i<nhanViens.size();i++){
            var nhanVien = nhanViens.get(i);
            data[i][0] = nhanVien.getId()+"";
            data[i][1] = nhanVien.getTen();
        }
        
        String[] cols = {"MNV", "Tên NV"};
        tm = new DefaultTableModel(data, cols);
        nhanVienTbl.setModel(tm);
        }
    }//GEN-LAST:event_timBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        (new TrangChuFrm()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void nhanVienTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhanVienTblMouseClicked
        // TODO add your handling code here:
        int row = nhanVienTbl.getSelectedRow();
        if (row >= 0 && row <= nhanVienTbl.getRowCount()-1) {
            int id = Integer.parseInt(tm.getValueAt(row, 0).toString());
            (new DangKyCaLamFrm(dangKyCaLamDAO.getNhanVienById(id))).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_nhanVienTblMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable nhanVienTbl;
    private javax.swing.JTextField tenTxt;
    private javax.swing.JButton timBtn;
    // End of variables declaration//GEN-END:variables
}
